name: Loki (Visual Regression Test)

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    name: loki test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: 'yarn'

      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: beta

      - name: yarn install
        run: yarn install

      - name: loki test
        run: yarn test:loki

      - name: argos upload
        if: failure()
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
          ARGOS_BRANCH: ${{ github.head_ref || github.ref }}
          ARGOS_COMMIT: ${{ github.sha }}
        run: |
          yarn argos upload .loki/difference
