name: Publish site

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish site
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Build project
        run: |
          yarn install
          yarn build

      - name: Build site
        run: yarn site:build

      - name: Deploy site
        run: yarn site:deploy
