name: Build CI

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Build project
        run: |
          yarn install
          yarn build

      - name: Build site
        run: yarn site:build

      - name: Run tests
        run: yarn test

      - name: Upload codecov report
        uses: codecov/codecov-action@v1.5.2
